name: 同步镜像到阿里云ACR
on:
  workflow_dispatch:  # 手动触发
    inputs:
      image_name:
        description: "要同步的镜像（格式：源镜像名:标签，如 nginx:latest）"
        required: true
        default: "joplin/server:latest"  # 测试用镜像

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 同步镜像到阿里云ACR
        uses: ikrong/docker-sync-action@main
        with:
          # 源镜像配置（以Docker Hub公共镜像为例）
          src_registry: "docker.io"  # 公共镜像源（无需认证）
          src_repo: ${{ github.event.inputs.image_name }}  # 源镜像名:标签
          src_username: ""  # 公共仓库无需用户名
          src_password: ""  # 公共仓库无需密码

          # 目标镜像配置（阿里云ACR）
          dest_registry: "crpi-te5263t1tjwbqtd9.cn-guangzhou.personal.cr.aliyuncs.com"  # 你的ACR Registry地址
          dest_repo: "1panel-apps/${{ github.event.inputs.image_name }}"  # 目标路径：命名空间/源镜像名:标签
          dest_username: LTAI5tSPLLKM7ngHyj8GkY6o
          dest_password: HrW70wa5e4ak9BHm6oD58pW7JtLeuu

          # 其他可选配置
          debug: "true"  # 开启调试模式（输出详细日志）
          timeout: "300"  # 超时时间（秒）
